src.dir := ../decode
top.sv := ../decode/test.sv

module.sv := \
	$(top.sv) \
	$(foreach dir,$(src.dir), \
	  	$(filter-out $(dir)/$(top.sv), \
			$(wildcard $(dir)/*.sv)))


module.v := \
	$(patsubst %.sv,v/%.v,\
		$(foreach file,$(module.sv),\
			$(notdir $(file))))

all: $(module.v)

clean:
	$(RM) $(module.v)

v/:
	mkdir -p v
	

define target

v/%.v : $1/%.sv | v/
	sv2v --define=SYNTHESIS --write=$$@ $$<

endef

$(foreach dir,$(src.dir), \
	$(eval $(call target,$(dir))))
